//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleStoryHelper.Standard.Resources.Properties {
    using MapleStoryHelper.Standard.Character;
    using MapleStoryHelper.Standard.Item.Equipment;
    using MapleStoryHelper.Standard.Resources.Attributes;
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapleStoryHelperResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapleStoryHelperResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleStoryHelper.Standard.Resources.Properties.MapleStoryHelperResource", typeof(MapleStoryHelperResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        #region Ring

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("결속의 반지", "", EEquipmentCategory.Ring)]
        public static byte[] Item_SynergyRing {
            get {
                object obj = ResourceManager.GetObject("결속의_반지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("마이스터링", "", EEquipmentCategory.Ring)]
        public static byte[] Item_MeisterRing {
            get {
                object obj = ResourceManager.GetObject("마이스터링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("벤전스링", "01114301", EEquipmentCategory.Ring)]
        public static byte[] Item_VengeanceRing {
            get {
                object obj = ResourceManager.GetObject("벤전스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        //[ResourceInfo("오닉스링", "", EEquipmentCategory.Ring)]
        //public static byte[] Item_OnyxRing {
        //    get {
        //        object obj = ResourceManager.GetObject("오닉스링", resourceCulture);
        //        return ((byte[])(obj));
        //    }
        //}

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("카오스링", "01114306", EEquipmentCategory.Ring)]
        public static byte[] Item_ChaosRing {
            get {
                object obj = ResourceManager.GetObject("카오스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("코스모스링", "01114304", EEquipmentCategory.Ring)]
        public static byte[] Item_CosmosRing {
            get {
                object obj = ResourceManager.GetObject("코스모스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [ResourceInfo("테네브리스 원정대 반지", "01114311", EEquipmentCategory.Ring)]
        public static byte[] Item_TenebrisRing 
        {
            get
            {
                object obj = ResourceManager.GetObject("테네브리스_원정대_반지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("실버블라썸 링", "01113149", EEquipmentCategory.Ring)]
        public static byte[] Item_SilverBlossomRing
        {
            get
            {
                object obj = ResourceManager.GetObject("실버블라썸_링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("실버블라썸 링", "01113149", EEquipmentCategory.Ring)]
        public static object Xml_SilverBlossomRing
        {
            get => ResourceManager.GetObject("01113149", resourceCulture);
        }

        [ResourceInfo("테네브리스 원정대 반지", "01114311", EEquipmentCategory.Ring)]
        public static object Xml_TenebrisRing
        {
            get => ResourceManager.GetObject("01114311", resourceCulture);
        }

        [ResourceInfo("벤전스링", "01114301", EEquipmentCategory.Ring)]
        public static object Xml_VengeanceRing
        {
            get => ResourceManager.GetObject("01114301", resourceCulture);
        }

        [ResourceInfo("카오스 링", "01114306", EEquipmentCategory.Ring)]
        public static object Xml_ChaosRing
        {
            get => ResourceManager.GetObject("01114306", resourceCulture);
        }

        #endregion

        #region Pocket


        [ResourceInfo("저주받은 적의 마도서", "1162080", EEquipmentCategory.Pocket)]
        public static byte[] Item_RedMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 적의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("저주받은 청의 마도서", "1162081", EEquipmentCategory.Pocket)]
        public static byte[] Item_BlueMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 청의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("저주받은 녹의 마도서", "1162082", EEquipmentCategory.Pocket)]
        public static byte[] Item_GreenMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 녹의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("저주받은 황의 마도서", "1162083", EEquipmentCategory.Pocket)]
        public static byte[] Item_YellowMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 황의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        #endregion

        #region Pendant

        [ResourceInfo("고통의 근원", "01122430", EEquipmentCategory.Pendant)]
        public static byte[] Item_SourceOfSuffering
        {
            get
            {
                object obj = ResourceManager.GetObject("고통의 근원", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("매커네이터 펜던트", "01122254", EEquipmentCategory.Pendant)]
        public static byte[] Item_MechanatorPendant
        {
            get
            {
                object obj = ResourceManager.GetObject("매커네이터 펜던트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("도미네이터 펜던트", "01122377", EEquipmentCategory.Pendant)]
        public static byte[] Item_DominatorPendant
        {
            get
            {
                object obj = ResourceManager.GetObject("도미네이터 펜던트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("도미네이터 펜던트", "01122377", EEquipmentCategory.Pendant)]
        public static object Xml_DominatorPendant
        {
            get => ResourceManager.GetObject("01122377", resourceCulture);
        }

        #endregion

        #region Weapon

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(도적)", "01242124", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static byte[] Item_Absolabs_EnergySword_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 에너지소드", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(도적)", "01242124", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static byte[] Item_Absolabs_EnergySword_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 에너지소드", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(도적)", "01242124", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static object Xml_Absolabs_EnergySword_Thief
        {
            get => ResourceManager.GetObject("01242124", resourceCulture);
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(해적)", "01242123", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0 ,1.5)]
        public static object Xml_Absolabs_EnergySword_Pirate
        {
            get => ResourceManager.GetObject("01242123", resourceCulture);
        }

        #endregion

        #region Belt

        [ResourceInfo("타일런트 벨트", "01132178", EEquipmentCategory.Belt)]
        public static byte[] Item_TylentBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("타일런트 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("타일런트 벨트", "01132178", EEquipmentCategory.Belt)]
        public static object Xml_TylentBelt
        {
            get => ResourceManager.GetObject("01132178", resourceCulture);
        }

        [ResourceInfo("몽환의 벨트", "01242123", EEquipmentCategory.Belt)]
        public static byte[] Item_DreamyBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("몽환의 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("분노한 자쿰의 벨트", "01242123", EEquipmentCategory.Belt)]
        public static byte[] Item_EnragedZakumBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("분노한 자쿰의 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("골든 클로버 벨트", "01242123", EEquipmentCategory.Belt)]
        public static byte[] Item_GoldenCloverBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("골든 클로버 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        #endregion

        #region Cap

        [EquipmentResourceInfoAttribute("아케인셰이드 나이트햇", "01004808", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_ArcaneShadeCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 나이트햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 메이지햇", "01004809", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_ArcaneShadeCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 메이지햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 아처햇", "01004810", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_ArcaneShadeCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 아처햇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        

        [EquipmentResourceInfoAttribute("아케인셰이드 시프햇", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_ArcaneShadeCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 시프햇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("아케인셰이드 파이렛햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_ArcaneShadeCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 파이렛햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트헬름", "01242124", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_AbsolabsCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 나이트헬름", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처후드", "01242123", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_AbsolabsCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 아처후드", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("앱솔랩스 메이지크라운", "01242124", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_AbsolabsCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 메이지크라운", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프캡", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_AbsolabsCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 시프캡", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛페도라", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_AbsolabsCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 파이렛페도라", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 워리어헬름", "01242124", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 워리어헬름", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 레인져베레", "01242123", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 레인져베레", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("하이네스 던위치햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 던위치햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 어새신보닛", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 어새신보닛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("하이네스 원더러햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 원더러햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 나이트햇", "01004808", EEquipmentCategory.Cap, (EJobCategory)1, 0)]
        public static object Xml_ArcaneShadeCap_Worrior
        {
            get => ResourceManager.GetObject("01242124", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 에너지소드(해적)", "01004809", EEquipmentCategory.Cap, (EJobCategory)2, 0)]
        public static object Xml_ArcaneShadeCap_Magician
        {
            get => ResourceManager.GetObject("01242123", resourceCulture);
        }

        #endregion


        #region Soulder

        [ResourceInfo("로얄 블랙메탈 숄더", "01152170", EEquipmentCategory.Shoulder)]
        public static byte[] Item_RoyalBlackMetalShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("로얄 블랙메탈 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("로얄 블랙메탈 숄더", "01152170", EEquipmentCategory.Shoulder)]
        public static object Xml_RoyalBlackMetalShoulder
        {
            get => ResourceManager.GetObject("01152170", resourceCulture);
        }

        [ResourceInfo("스칼렛 숄더", "01182193", EEquipmentCategory.Shoulder)]
        public static byte[] Item_ScaletShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("스칼렛 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("스칼렛 숄더", "01152155", EEquipmentCategory.Shoulder)]
        public static object Xml_ScaletShoulder
        {
            get => ResourceManager.GetObject("01152155", resourceCulture);
        }

        [ResourceInfo("앱솔랩스 숄더", "01152174", EEquipmentCategory.Shoulder)]
        public static byte[] Item_AbsolabsShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("앱솔랩스 숄더", "01152174", EEquipmentCategory.Shoulder)]
        public static object Xml_AbsolabsShoulder
        {
            get => ResourceManager.GetObject("01152174", resourceCulture);
        }

        [ResourceInfo("아케인셰이드 숄더", "01152196", EEquipmentCategory.Shoulder)]
        public static byte[] Item_ArcaneShadeShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("아케인셰이드 숄더", "01152196", EEquipmentCategory.Shoulder)]
        public static object Xml_ArcaneShadeShoulder
        {
            get => ResourceManager.GetObject("01152196", resourceCulture);
        }


        #endregion

        #region Badge

        [ResourceInfo("뱃지 오브 마노", "01182193", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfMano
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 마노", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 마노", "01182193", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfMano
        {
            get => ResourceManager.GetObject("01182193", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 치우", "01182194", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfChiu
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 치우", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 치우", "01182194", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfChiu
        {
            get => ResourceManager.GetObject("01182194", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 보탄", "01182195", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfBotan
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 보탄", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 보탄", "01182195", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfBotan
        {
            get => ResourceManager.GetObject("01182195", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 도나르", "01182196", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfDonar
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 도나르", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 도나르", "01182196", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfDonar
        {
            get => ResourceManager.GetObject("01182196", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 프루바", "01182197", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfPruba
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 프루바", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 프루바", "01182197", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfPruba
        {
            get => ResourceManager.GetObject("01182197", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 사투르누스", "01182198", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfSaturnus
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 사투르누스", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 사투르누스", "01182198", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfSaturnus
        {
            get => ResourceManager.GetObject("01182198", resourceCulture);
        }

        [ResourceInfo("뱃지 오브 준나", "01182199", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfJuna
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 준나", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("뱃지 오브 준나", "01182199", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfJuna
        {
            get => ResourceManager.GetObject("01182199", resourceCulture);
        }

        [ResourceInfo("칠요의 뱃지", "01182200", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfWeek
        {
            get
            {
                object obj = ResourceManager.GetObject("칠요의 뱃지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("칠요의 뱃지", "01182200", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfWeek
        {
            get => ResourceManager.GetObject("01182200", resourceCulture);
        }

        [ResourceInfo("창세의 뱃지", "01182285", EEquipmentCategory.Badge)]
        public static byte[] Item_BadgeOfGenesis
        {
            get
            {
                object obj = ResourceManager.GetObject("창세의 뱃지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [ResourceInfo("창세의 뱃지", "01182285", EEquipmentCategory.Badge)]
        public static object Xml_BadgeOfGenesis
        {
            get => ResourceManager.GetObject("01182285", resourceCulture);
        }

        #endregion

        public static object Txt_ItemCodes
        {
            get => ResourceManager.GetObject("MapleStoryItemCodes", resourceCulture);
        }

        public static object Xml_EqpString
        {
            get => ResourceManager.GetObject("Eqp", resourceCulture);
        }
    }
}
