//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapleStoryHelper.Standard.Resources.Properties {
    using MapleStoryHelper.Standard.Character;
    using MapleStoryHelper.Standard.Item.Equipment;
    using MapleStoryHelper.Standard.Resources.Attributes;
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MapleStoryHelperResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapleStoryHelperResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapleStoryHelper.Standard.Resources.Properties.MapleStoryHelperResource", typeof(MapleStoryHelperResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        #region Ring

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("결속의 반지", "", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_SynergyRing {
            get {
                object obj = ResourceManager.GetObject("결속의_반지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("마이스터링", "", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_MeisterRing {
            get {
                object obj = ResourceManager.GetObject("마이스터링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("벤전스링", "01114301", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_VengeanceRing {
            get {
                object obj = ResourceManager.GetObject("벤전스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        //[EquipmentResourceInfoAttribute("오닉스링", "", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        //public static byte[] Item_OnyxRing {
        //    get {
        //        object obj = ResourceManager.GetObject("오닉스링", resourceCulture);
        //        return ((byte[])(obj));
        //    }
        //}

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("카오스링", "01114306", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_ChaosRing {
            get {
                object obj = ResourceManager.GetObject("카오스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("코스모스링", "01114304", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_CosmosRing {
            get {
                object obj = ResourceManager.GetObject("코스모스링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        [EquipmentResourceInfoAttribute("테네브리스 원정대 반지", "01114311", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_TenebrisRing 
        {
            get
            {
                object obj = ResourceManager.GetObject("테네브리스_원정대_반지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("실버블라썸 링", "01113149", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static byte[] Item_SilverBlossomRing
        {
            get
            {
                object obj = ResourceManager.GetObject("실버블라썸_링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("실버블라썸 링", "01113149", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static object Xml_SilverBlossomRing
        {
            get => ResourceManager.GetObject("01113149", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("테네브리스 원정대 반지", "01114311", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static object Xml_TenebrisRing
        {
            get => ResourceManager.GetObject("01114311", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("벤전스링", "01114301", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static object Xml_VengeanceRing
        {
            get => ResourceManager.GetObject("01114301", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("카오스 링", "01114306", EEquipmentCategory.Ring, EJobCategory.All, 0)]
        public static object Xml_ChaosRing
        {
            get => ResourceManager.GetObject("01114306", resourceCulture);
        }

        #endregion

        #region Pocket

        [EquipmentResourceInfoAttribute("핑크빛 성배", "01162025", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static byte[] Item_PinkChalice
        {
            get
            {
                object obj = ResourceManager.GetObject("핑크빛 성배", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("핑크빛 성배", "01162025", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static object Xml_PinkChalice
        {
            get => ResourceManager.GetObject("01162025", resourceCulture);
        }


        [EquipmentResourceInfoAttribute("저주받은 적의 마도서", "01162080", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static byte[] Item_RedMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 적의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("저주받은 적의 마도서", "01162080", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static object Xml_RedMagicBook
        {
            get => ResourceManager.GetObject("01162080", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("저주받은 청의 마도서", "01162081", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static byte[] Item_BlueMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 청의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("저주받은 청의 마도서", "01162081", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static object Xml_BlueMagicBook
        {
            get => ResourceManager.GetObject("01162081", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("저주받은 녹의 마도서", "01162082", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static byte[] Item_GreenMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 녹의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("저주받은 녹의 마도서", "01162082", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static object Xml_GreenMagicBook
        {
            get => ResourceManager.GetObject("01162082", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("저주받은 황의 마도서", "01162083", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static byte[] Item_YellowMagicBook
        {
            get
            {
                object obj = ResourceManager.GetObject("저주받은 황의 마도서", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("저주받은 황의 마도서", "01162083", EEquipmentCategory.Pocket, EJobCategory.All, 0)]
        public static object Xml_YellowMagicBook
        {
            get => ResourceManager.GetObject("01162083", resourceCulture);
        }

        #endregion

        #region Pendant

        [EquipmentResourceInfoAttribute("고통의 근원", "01122430", EEquipmentCategory.Pendant, EJobCategory.All, 0)]
        public static byte[] Item_SourceOfSuffering
        {
            get
            {
                object obj = ResourceManager.GetObject("고통의 근원", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("매커네이터 펜던트", "01122254", EEquipmentCategory.Pendant, EJobCategory.All, 0)]
        public static byte[] Item_MechanatorPendant
        {
            get
            {
                object obj = ResourceManager.GetObject("매커네이터 펜던트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("도미네이터 펜던트", "01122377", EEquipmentCategory.Pendant, EJobCategory.All, 0)]
        public static byte[] Item_DominatorPendant
        {
            get
            {
                object obj = ResourceManager.GetObject("도미네이터 펜던트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("도미네이터 펜던트", "01122377", EEquipmentCategory.Pendant, EJobCategory.All, 0)]
        public static object Xml_DominatorPendant
        {
            get => ResourceManager.GetObject("01122377", resourceCulture);
        }

        #endregion

        #region Weapon

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(도적)", "01242124", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static byte[] Item_Absolabs_EnergySword_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 에너지소드", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(해적)", "01242123", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static byte[] Item_Absolabs_EnergySword_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 에너지소드", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(도적)", "01242124", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0, 1.5)]
        public static object Xml_Absolabs_EnergySword_Thief
        {
            get => ResourceManager.GetObject("01242124", resourceCulture);
        }

        [WeaponResourceInfoAttribute("앱솔랩스 에너지소드(해적)", "01242123", EEquipmentCategory.Weapon, EJobCategory.Xenon, 0 ,1.5)]
        public static object Xml_Absolabs_EnergySword_Pirate
        {
            get => ResourceManager.GetObject("01242123", resourceCulture);
        }

        #endregion

        #region Belt

        [EquipmentResourceInfoAttribute("타일런트 벨트", "01132178", EEquipmentCategory.Belt, EJobCategory.All, 0)]
        public static byte[] Item_TylentBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("타일런트 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("타일런트 벨트", "01132178", EEquipmentCategory.Belt, EJobCategory.All, 0)]
        public static object Xml_TylentBelt
        {
            get => ResourceManager.GetObject("01132178", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("몽환의 벨트", "01242123", EEquipmentCategory.Belt, EJobCategory.All, 0)]
        public static byte[] Item_DreamyBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("몽환의 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("분노한 자쿰의 벨트", "01242123", EEquipmentCategory.Belt, EJobCategory.All, 0)]
        public static byte[] Item_EnragedZakumBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("분노한 자쿰의 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("골든 클로버 벨트", "01242123", EEquipmentCategory.Belt, EJobCategory.All, 0)]
        public static byte[] Item_GoldenCloverBelt
        {
            get
            {
                object obj = ResourceManager.GetObject("골든 클로버 벨트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        #endregion

        #region Cap

        [EquipmentResourceInfoAttribute("아케인셰이드 나이트햇", "01004808", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_ArcaneShadeCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 나이트햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 메이지햇", "01004809", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_ArcaneShadeCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 메이지햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 아처햇", "01004810", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_ArcaneShadeCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 아처햇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        

        [EquipmentResourceInfoAttribute("아케인셰이드 시프햇", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_ArcaneShadeCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 시프햇", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("아케인셰이드 파이렛햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_ArcaneShadeCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 파이렛햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트헬름", "01242124", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_AbsolabsCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 나이트헬름", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처후드", "01242123", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_AbsolabsCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 아처후드", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("앱솔랩스 메이지크라운", "01242124", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_AbsolabsCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 메이지크라운", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프캡", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_AbsolabsCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 시프캡", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛페도라", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_AbsolabsCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 파이렛페도라", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 워리어헬름", "01242124", EEquipmentCategory.Cap, EJobCategory.Worrior, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Worrior
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 워리어헬름", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 레인져베레", "01242123", EEquipmentCategory.Cap, EJobCategory.Archer, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Archer
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 레인져베레", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("하이네스 던위치햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Magician, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Magician
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 던위치햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("하이네스 어새신보닛", "01242123", EEquipmentCategory.Cap, EJobCategory.Thief, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Thief
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 어새신보닛", resourceCulture);
                return ((byte[])(obj));
            }
        }
        [EquipmentResourceInfoAttribute("하이네스 원더러햇", "01242124", EEquipmentCategory.Cap, EJobCategory.Pirate, 0)]
        public static byte[] Item_ChaosRootAbyssCap_Pirate
        {
            get
            {
                object obj = ResourceManager.GetObject("하이네스 원더러햇", resourceCulture);
                return ((byte[])(obj));
            }
        }

        #endregion

        #region Face

        [EquipmentResourceInfoAttribute("루즈 컨트롤 머신 마크", "01012632", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static byte[] Item_LoseControlMark
        {
            get
            {
                object obj = ResourceManager.GetObject("루즈 컨트롤 머신 마크", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("루즈 컨트롤 머신 마크", "01012632", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static object Xml_LoseControlMark
        {
            get => ResourceManager.GetObject("01012632", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("응축된 힘의 결정석", "01012478", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static byte[] Item_StrengthCrystal
        {
            get
            {
                object obj = ResourceManager.GetObject("응축된 힘의 결정석", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("응축된 힘의 결정석", "01012478", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static object Xml_StrengthCrystal
        {
            get => ResourceManager.GetObject("01012478", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("마이스터 심볼", "01012410", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static byte[] Item_MeisterSymbol
        {
            get
            {
                object obj = ResourceManager.GetObject("마이스터 심볼", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("마이스터 심볼", "01012410", EEquipmentCategory.Face, EJobCategory.All, 0)]
        public static object Xml_MeisterSymbol
        {
            get => ResourceManager.GetObject("01012410", resourceCulture);
        }

        #endregion

        #region Eye

        [EquipmentResourceInfoAttribute("마력이 깃든 안대", "01022278", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static byte[] Item_MagicEyePath
        {
            get
            {
                object obj = ResourceManager.GetObject("마력이 깃든 안대", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("마력이 깃든 안대", "01022278", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static object Xml_MagicEyePath
        {
            get => ResourceManager.GetObject("01022278", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("파풀라투스 마크", "01022277", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static byte[] Item_PapulatusMark
        {
            get
            {
                object obj = ResourceManager.GetObject("파풀라투스 마크", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("파풀라투스 마크", "01022277", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static object Xml_PapulatusMark
        {
            get => ResourceManager.GetObject("01022277", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아쿠아틱 레터 눈장식", "01022231", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static byte[] Item_AquaticLetterEye
        {
            get
            {
                object obj = ResourceManager.GetObject("아쿠아틱 레터 눈장식", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아쿠아틱 레터 눈장식", "01022231", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static object Xml_AquaticLetterEye
        {
            get => ResourceManager.GetObject("01022231", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("블랙빈 마크", "01022232", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static byte[] Item_BlackBeanMark
        {
            get
            {
                object obj = ResourceManager.GetObject("블랙빈 마크", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("블랙빈 마크", "01022232", EEquipmentCategory.Eye, EJobCategory.All, 0)]
        public static object Xml_BlackBeanMark
        {
            get => ResourceManager.GetObject("01022232", resourceCulture);
        }

        #endregion

        #region Clothes

        [EquipmentResourceInfoAttribute("아케인셰이드 나이트슈트", "01053063", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static byte[] Item_ArcaneShadeKnightSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 나이트슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 나이트슈트", "01053063", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static object Xml_ArcaneShadeKnightSuit
        {
            get => ResourceManager.GetObject("01053063", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 메이지슈트", "01053064", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static byte[] Item_ArcaneShadeMagicianSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 메이지슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 메이지슈트", "01053064", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static object Xml_ArcaneShadeMagicianSuit
        {
            get => ResourceManager.GetObject("01053064", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 아처슈트", "01053065", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static byte[] Item_ArcaneShadeArcherSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 아처슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 아처슈트", "01053065", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static object Xml_ArcaneShadeArcherSuit
        {
            get => ResourceManager.GetObject("01053065", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 시프슈트", "01053066", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static byte[] Item_ArcaneShadeThiefSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 시프슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 시프슈트", "01053066", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static object Xml_ArcaneShadeThiefSuit
        {
            get => ResourceManager.GetObject("01053066", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 파이렛슈트", "01053067", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static byte[] Item_ArcaneShadePirateSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 파이렛슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 파이렛슈트", "01053067", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static object Xml_ArcaneShadePirateSuit
        {
            get => ResourceManager.GetObject("01053067", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트슈트", "01052882", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static byte[] Item_AbsolabsKnightSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 나이트슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트슈트", "01052882", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static object Xml_AbsolabsKnightSuit
        {
            get => ResourceManager.GetObject("01052882", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 메이지슈트", "01052887", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static byte[] Item_AbsolabsMagicianSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 메이지슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 메이지슈트", "01052887", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static object Xml_AbsolabsMagicianSuit
        {
            get => ResourceManager.GetObject("01052887", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처슈트", "01052888", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static byte[] Item_AbsolabsArcherSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 아처슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처슈트", "01052888", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static object Xml_AbsolabsArcherSuit
        {
            get => ResourceManager.GetObject("01052888", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프슈트", "01052889", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static byte[] Item_AbsolabsThiefSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 시프슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프슈트", "01052889", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static object Xml_AbsolabsThiefSuit
        {
            get => ResourceManager.GetObject("01052889", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛슈트", "01052890", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static byte[] Item_AbsolabsPirateSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 파이렛슈트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛슈트", "01052890", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static object Xml_AbsolabsPirateSuit
        {
            get => ResourceManager.GetObject("01052890", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("이글아이 워리어아머", "01042392", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static byte[] Item_EagleEyeKnightSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("이글아이 워리어아머", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("이글아이 워리어아머", "01042392", EEquipmentCategory.Clothes, EJobCategory.Worrior, 0)]
        public static object Xml_EagleEyeKnightSuit
        {
            get => ResourceManager.GetObject("01042392", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("이글아이 던위치로브", "01042393", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static byte[] Item_EagleEyeMagicianSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("이글아이 던위치로브", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("이글아이 던위치로브", "01042393", EEquipmentCategory.Clothes, EJobCategory.Magician, 0)]
        public static object Xml_EagleEyeMagicianSuit
        {
            get => ResourceManager.GetObject("01042393", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("이글아이 레인저후드", "01042394", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static byte[] Item_EagleEyeArcherSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("이글아이 레인저후드", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("이글아이 레인저후드", "01042394", EEquipmentCategory.Clothes, EJobCategory.Archer, 0)]
        public static object Xml_EagleEyeArcherSuit
        {
            get => ResourceManager.GetObject("01042394", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("이글아이 어새신셔츠", "01042395", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static byte[] Item_EagleEyeThiefSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("이글아이 어새신셔츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("이글아이 어새신셔츠", "01042395", EEquipmentCategory.Clothes, EJobCategory.Thief, 0)]
        public static object Xml_EagleEyeThiefSuit
        {
            get => ResourceManager.GetObject("01042395", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("이글아이 원더러코트", "01042396", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static byte[] Item_EagleEyePirateSuit
        {
            get
            {
                object obj = ResourceManager.GetObject("이글아이 원더러코트", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("이글아이 원더러코트", "01042396", EEquipmentCategory.Clothes, EJobCategory.Pirate, 0)]
        public static object Xml_EagleEyePirateSuit
        {
            get => ResourceManager.GetObject("01042396", resourceCulture);
        }

        #endregion

        #region Pants

        [EquipmentResourceInfoAttribute("트릭스터 워리어팬츠", "01062253", EEquipmentCategory.Pants, EJobCategory.Worrior, 0)]
        public static byte[] Item_TrixterWorriorPants
        {
            get
            {
                object obj = ResourceManager.GetObject("트릭스터 워리어팬츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("트릭스터 워리어팬츠", "01062253", EEquipmentCategory.Pants, EJobCategory.Worrior, 0)]
        public static object Xml_TrixterWorriorPants
        {
            get => ResourceManager.GetObject("01062253", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("트릭스터 던위치팬츠", "01062254", EEquipmentCategory.Pants, EJobCategory.Magician, 0)]
        public static byte[] Item_TrixterWitchPants
        {
            get
            {
                object obj = ResourceManager.GetObject("트릭스터 던위치팬츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("트릭스터 던위치팬츠", "01062254", EEquipmentCategory.Pants, EJobCategory.Magician, 0)]
        public static object Xml_TrixterWitchPants
        {
            get => ResourceManager.GetObject("01062254", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("트릭스터 레인져팬츠", "01062255", EEquipmentCategory.Pants, EJobCategory.Archer, 0)]
        public static byte[] Item_TrixterRangerPants
        {
            get
            {
                object obj = ResourceManager.GetObject("트릭스터 레인져팬츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("트릭스터 레인져팬츠", "01062255", EEquipmentCategory.Pants, EJobCategory.Archer, 0)]
        public static object Xml_TrixterRangerPants
        {
            get => ResourceManager.GetObject("01062255", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("트릭스터 어새신팬츠", "01062256", EEquipmentCategory.Pants, EJobCategory.Thief
            , 0)]
        public static byte[] Item_TrixterAssassinPants
        {
            get
            {
                object obj = ResourceManager.GetObject("트릭스터 어새신팬츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("트릭스터 어새신팬츠", "01062256", EEquipmentCategory.Pants, EJobCategory.Thief, 0)]
        public static object Xml_TrixterAssassinPants
        {
            get => ResourceManager.GetObject("01062256", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("트릭스터 원더러팬츠", "01062257", EEquipmentCategory.Pants, EJobCategory.Pirate, 0)]
        public static byte[] Item_TrixterPiratePants
        {
            get
            {
                object obj = ResourceManager.GetObject("트릭스터 원더러팬츠", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("트릭스터 원더러팬츠", "01062257", EEquipmentCategory.Pants, EJobCategory.Pirate, 0)]
        public static object Xml_TrixterPiratePants
        {
            get => ResourceManager.GetObject("01062257", resourceCulture);
        }

        #endregion

        #region Shoes

        [EquipmentResourceInfoAttribute("타일런트 신발", "01072747", EEquipmentCategory.Shoes, EJobCategory.All, 0)]
        public static byte[] Item_TylentShoes
        {
            get
            {
                object obj = ResourceManager.GetObject("타일런트 신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("타일런트 신발", "01072747", EEquipmentCategory.Shoes, EJobCategory.All, 0)]
        public static object Xml_TylentShoes
        {
            get => ResourceManager.GetObject("01072747", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트슈즈", "01073030", EEquipmentCategory.Shoes, EJobCategory.Worrior, 0)]
        public static byte[] Item_AbsolabsShoes_W
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 나이트슈즈", "01073030", EEquipmentCategory.Shoes, EJobCategory.Worrior, 0)]
        public static object Xml_AbsolabsShoes_W
        {
            get => ResourceManager.GetObject("01073030", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 메이지슈즈", "01073032", EEquipmentCategory.Shoes, EJobCategory.Magician, 0)]
        public static byte[] Item_AbsolabsShoes_M
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 메이지슈즈", "01073032", EEquipmentCategory.Shoes, EJobCategory.Magician, 0)]
        public static object Xml_AbsolabsShoes_M
        {
            get => ResourceManager.GetObject("01073032", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처슈즈", "01073033", EEquipmentCategory.Shoes, EJobCategory.Archer, 0)]
        public static byte[] Item_AbsolabsShoes_A
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 아처슈즈", "01073033", EEquipmentCategory.Shoes, EJobCategory.Archer, 0)]
        public static object Xml_AbsolabsShoes_A
        {
            get => ResourceManager.GetObject("01073033", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프슈즈", "01073034", EEquipmentCategory.Shoes, EJobCategory.Thief, 0)]
        public static byte[] Item_AbsolabsShoes_T
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 시프슈즈", "01073034", EEquipmentCategory.Shoes, EJobCategory.Thief, 0)]
        public static object Xml_AbsolabsShoes_T
        {
            get => ResourceManager.GetObject("01073034", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛슈즈", "01073035", EEquipmentCategory.Shoes, EJobCategory.Pirate, 0)]
        public static byte[] Item_AbsolabsShoes_P
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔신발", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 파이렛슈즈", "01073035", EEquipmentCategory.Shoes, EJobCategory.Pirate, 0)]
        public static object Xml_AbsolabsShoes_P
        {
            get => ResourceManager.GetObject("01073035", resourceCulture);
        }

        #endregion

        #region Ear

        [EquipmentResourceInfoAttribute("커맨더 포스 이어링", "01032316", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static byte[] Item_CommanderForceEar
        {
            get
            {
                object obj = ResourceManager.GetObject("커맨더 포스 이어링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("커맨더 포스 이어링", "01032316", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static object Xml_CommanderForceEar
        {
            get => ResourceManager.GetObject("01032316", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("지옥의 불꽃", "01032136", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static byte[] Item_FlameOfHell
        {
            get
            {
                object obj = ResourceManager.GetObject("지옥의 불꽃", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("지옥의 불꽃", "01032136", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static object Xml_FlameOfHell
        {
            get => ResourceManager.GetObject("01032136", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("스칼렛 이어링", "01032216", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static byte[] Item_ScarletEar
        {
            get
            {
                object obj = ResourceManager.GetObject("스칼렛 이어링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("스칼렛 이어링", "01032216", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static object Xml_ScarletEar
        {
            get => ResourceManager.GetObject("01032216", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("마이스터 이어링", "01032200", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static byte[] Item_MeisterEar
        {
            get
            {
                object obj = ResourceManager.GetObject("마이스터 이어링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("마이스터 이어링", "01032200", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static object Xml_MeisterEar
        {
            get => ResourceManager.GetObject("01032200", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("데아 시두스 이어링", "01032241", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static byte[] Item_DeaSidusEar
        {
            get
            {
                object obj = ResourceManager.GetObject("데아 시두스 이어링", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("데아 시두스 이어링", "01032241", EEquipmentCategory.Ear, EJobCategory.All, 0)]
        public static object Xml_DeaSidusEar
        {
            get => ResourceManager.GetObject("01032241", resourceCulture);
        }

        #endregion

        #region Soulder

        [EquipmentResourceInfoAttribute("로얄 블랙메탈 숄더", "01152170", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static byte[] Item_RoyalBlackMetalShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("로얄 블랙메탈 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("로얄 블랙메탈 숄더", "01152170", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static object Xml_RoyalBlackMetalShoulder
        {
            get => ResourceManager.GetObject("01152170", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("마이스터 숄더", "01152154", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static byte[] Item_MeisterShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("마이스터 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("마이스터 숄더", "01152154", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static object Xml_MeisterShoulder
        {
            get => ResourceManager.GetObject("01152154", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("스칼렛 숄더", "01152155", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static byte[] Item_ScaletShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("스칼렛 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("스칼렛 숄더", "01152155", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static object Xml_ScaletShoulder
        {
            get => ResourceManager.GetObject("01152155", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 숄더", "01152174", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static byte[] Item_AbsolabsShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔랩스 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 숄더", "01152174", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static object Xml_AbsolabsShoulder
        {
            get => ResourceManager.GetObject("01152174", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 숄더", "01152196", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static byte[] Item_ArcaneShadeShoulder
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 숄더", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 숄더", "01152196", EEquipmentCategory.Shoulder, EJobCategory.All, 0)]
        public static object Xml_ArcaneShadeShoulder
        {
            get => ResourceManager.GetObject("01152196", resourceCulture);
        }


        #endregion

        #region Badge

        [EquipmentResourceInfoAttribute("뱃지 오브 마노", "01182193", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfMano
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 마노", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 마노", "01182193", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfMano
        {
            get => ResourceManager.GetObject("01182193", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 치우", "01182194", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfChiu
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 치우", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 치우", "01182194", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfChiu
        {
            get => ResourceManager.GetObject("01182194", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 보탄", "01182195", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfBotan
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 보탄", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 보탄", "01182195", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfBotan
        {
            get => ResourceManager.GetObject("01182195", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 도나르", "01182196", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfDonar
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 도나르", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 도나르", "01182196", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfDonar
        {
            get => ResourceManager.GetObject("01182196", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 프루바", "01182197", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfPruba
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 프루바", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 프루바", "01182197", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfPruba
        {
            get => ResourceManager.GetObject("01182197", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 사투르누스", "01182198", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfSaturnus
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 사투르누스", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 사투르누스", "01182198", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfSaturnus
        {
            get => ResourceManager.GetObject("01182198", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 준나", "01182199", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfJuna
        {
            get
            {
                object obj = ResourceManager.GetObject("뱃지 오브 준나", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("뱃지 오브 준나", "01182199", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfJuna
        {
            get => ResourceManager.GetObject("01182199", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("칠요의 뱃지", "01182200", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfWeek
        {
            get
            {
                object obj = ResourceManager.GetObject("칠요의 뱃지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("칠요의 뱃지", "01182200", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfWeek
        {
            get => ResourceManager.GetObject("01182200", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("창세의 뱃지", "01182285", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static byte[] Item_BadgeOfGenesis
        {
            get
            {
                object obj = ResourceManager.GetObject("창세의 뱃지", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("창세의 뱃지", "01182285", EEquipmentCategory.Badge, EJobCategory.All, 0)]
        public static object Xml_BadgeOfGenesis
        {
            get => ResourceManager.GetObject("01182285", resourceCulture);
        }

        #endregion

        #region Cape

        [EquipmentResourceInfoAttribute("타일런트 망토", "01102481", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static byte[] Item_TylentCape
        {
            get
            {
                object obj = ResourceManager.GetObject("탈망", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("타일런트 망토", "01102481", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static object Xml_TylentCape
        {
            get => ResourceManager.GetObject("01102481", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 망토", "01102775", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static byte[] Item_AbsolabsCape
        {
            get
            {
                object obj = ResourceManager.GetObject("앱솔망토", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("앱솔랩스 망토", "01102775", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static object Xml_AbsolabsCape
        {
            get => ResourceManager.GetObject("01102775", resourceCulture);
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 망토", "01102940", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static byte[] Item_ArcaneShade
        {
            get
            {
                object obj = ResourceManager.GetObject("아케인셰이드 망토", resourceCulture);
                return ((byte[])(obj));
            }
        }

        [EquipmentResourceInfoAttribute("아케인셰이드 망토", "01102940", EEquipmentCategory.Cape, EJobCategory.All, 0)]
        public static object Xml_ArcaneShade
        {
            get => ResourceManager.GetObject("01102940", resourceCulture);
        }

        #endregion

        public static object Txt_ItemCodes
        {
            get => ResourceManager.GetObject("MapleStoryItemCodes", resourceCulture);
        }

        public static object Xml_EqpString
        {
            get => ResourceManager.GetObject("Eqp", resourceCulture);
        }
    }
}
